/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Cards: typeof import('./../src/components/Cards/Cards.vue')['default']
    CardsCards: typeof import('./../src/components/Cards/Cards.vue')['default']
    Modal: typeof import('./../src/components/Modal/Modal.vue')['default']
    ModalModal: typeof import('./../src/components/Modal/Modal.vue')['default']
    ModalPokemonInfo: typeof import('./../src/components/Modal/PokemonInfo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
